services:
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - dev-irl-network
    restart: unless-stopped

volumes:
  postgres_data_prod:

networks:
  dev-irl-network:
    external: true
