DROP TABLE IF EXISTS quests;

CREATE TABLE quests (
    id BIGSERIAL PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id),
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE bounty (
    id BIGSERIAL PRIMARY KEY,
    quest_id UUID NOT NULL REFERENCES users(id),
    base_reward NUMERIC NOT NULL,
    time_reward NUMERIC NOT NULL,
    success_reward NUMERIC NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE bounty (
    id BIGSERIAL PRIMARY KEY,
    quest_id UUID NOT NULL REFERENCES users(id),
    base_reward NUMERIC NOT NULL,
    time_reward NUMERIC NOT NULL,
    success_reward NUMERIC NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);